### ISSUE TITLE
Add headless hunt to the spelling bee page

### ISSUE THREAD

**Issue by ylong1211** [mcolen/headless-hunt#10]
https://www.nytimes.com/puzzles/spelling-bee

**Comment by mcolen** [comment]
Made the necessary code changes: https://github.com/mcolen/headless-hunt/commit/51e24bdd666ffcca654cf8b769a8730059ccf143.

Submitted the extension update for review by Google. The fix should be live when v0.5 is released.

**Comment by mcolen** [comment]
v0.5 is live on the Chrome Web Store: https://chrome.google.com/webstore/detail/headless-hunt/jiblconbnpebgkabogadmjcjhlbleljh?hl=en.
